#!/usr/bin/env python3
"""Compose ANALYSIS_functions.md from functions_final.csv, functions_final_stats.json, hooks_final.json, libc_members_placed.json."""
import csv, json, os, collections
BK = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/'
rows = list(csv.DictReader(open(BK + 'functions_final.csv')))
stats = json.load(open(BK + 'functions_final_stats.json'))
hooks = json.load(open(BK + 'hooks_final.json'))
lib = json.load(open(BK + 'libc_members_placed.json'))
cnt = stats['by_status']; byt = stats['bytes_by_status']
conf = collections.Counter((r['status'], r['confidence']) for r in rows)
def tbl(hdr, lines):
    out = ['| ' + ' | '.join(hdr) + ' |', '|' + '---|' * len(hdr)]
    out += ['| ' + ' | '.join(str(x).replace('|', '\\|') for x in l) + ' |' for l in lines]
    return '\n'.join(out)
md = []
md.append("# Final function map of dump_a.bin (Keychron V10 Max custom firmware, built 2024-07-09)\n")
md.append("Reconciliation of Method A (`functions_matched.csv`, masked signature matcher vs six gcc-15.2 reference builds) and Method B (`functions_linkorder.csv`, link-order alignment vs `ref1011_feat`), with two tie-breakers: Method C (`dump_symbols_gcc13.json`, `tools/match_ref_funcs.py` vs the xPack GCC 13.2.1 build `refs/ref1011_feat_gcc13.elf`) and the Ubuntu newlib 4.4.0 `libc_nano.a` member placement (`libc_members_placed.json`, `tools/libc_place.py`, from `lib_match.json`). Script: `tools/reconcile_maps.py` -> `functions_final.csv`, `functions_final_stats.json`; `tools/disasm_hooks.py` -> `hooks_final.json`, `disasm/*.txt`.\n")
md.append("Every address below is a flash address in `dump_a.bin` (file offset = address - 0x08000000). 'ref' = `refs/ref1011_feat.elf` unless stated. Verified facts cite the instructions they rest on; inferences are marked.\n")
md.append("## 1. Result in numbers\n")
md.append(f"* Rows in `functions_final.csv`: {stats['rows']} (functions, libc symbols, rodata/.data objects).")
md.append(f"* `.text` 0x08008000-0x08016704 = {stats['text_bytes']} B: {stats['text_named']} B named ({stats['text_named_pct']}%). The remaining 82 B are alignment padding (18 gaps of 2-40 zero/`nop` bytes between newlib members, e.g. 40 B of zeros at 0x08008698 before the 64-B-aligned `strlen`, and 2 B before `.rodata`).")
md.append(f"* Whole image 0x08008000-0x08017F04 = {stats['region_bytes']} B: {stats['region_named']} B named ({stats['region_named_pct']}%); the unnamed remainder is anonymous rodata/.data (strings, USB descriptors, ChibiOS config structs) that neither method sizes.")
md.append("* Status counts (rows / bytes): " + ', '.join(f"{k} {cnt[k]} / {byt[k]} B" for k in ['agreed', 'B-only', 'lib-only', 'conflict', 'A-only', 'data']) + '.')
md.append("* Confidence: " + ', '.join(f"{s}:{c}={n}" for (s, c), n in sorted(conf.items())) + '.')
md.append("* Method A alone had named 41.9% of the code region (exact+fuzzy) and Method B 88.1% of `.text`; the union plus the libc archive placement names 99.86% of `.text`. Where both named a function they agreed in 805 cases (A's `a|b|c` ambiguous sets count as agreement when B's link-order pick is a member - 130 such tiny identical-body functions: rgb effect wrappers, weak kb/user hooks, get_* accessors, layer_or/and/xor, register/unregister_mods).\n")
md.append("## 2. Genuine disagreements and how each was resolved\n")
md.append("All by disassembling the dump (`arm-none-eabi-objdump -D -b binary -m arm -M force-thumb --adjust-vma=0x08000000`) against the reference ELF. Winner in bold.\n")
C = [
 ('0x0800811C-0x08008124', 'A: Reset_Handler 2 B, BusFault_Handler 4 B, (_unhandled_exception 2 B) / B: INSERTION + "Reset_Handler split1/split2"', '**A**. Bytes `e770` (b.n 0x08008000 = _crt0_entry), `f000 f800` (bl 0x08008122), `e7fe` (b.n self) are instruction-identical to ref vectors.S; vector slot 1 = 0x0800811D, slots 2..15 (except SVC) = 0x0800811F.'),
 ('0x08008124-0x08008158', 'A: __port_switch 24, __port_thread_start 16, .zombies 2, __port_switch_from_isr 4, __port_exit_from_isr 6 / B: one 50-B chcoreasm.o section labelled __port_switch (+ INSERTION)', '**A** (finer, byte-identical to ref chcoreasm.S: `msr BASEPRI`, `blx r4`, `bl chThdExit`(0x08013A70), `bl chSchDoPreemption`(0x08013928), `svc 0`). Same object, so B is not wrong at object granularity.'),
 ('0x08008444', 'A: __aeabi_idiv0 / B: __aeabi_ldiv0', 'alias: both names sit on the same `bx lr` in libgcc _dvmd_tls.o (ref nm 0x08008434 W for both). Not a conflict.'),
 ('0x08008970 / 0x08008980', 'A: {free|malloc|raise} ambiguous / B: malloc, free', '**B**. 0x08008970 tail-calls 0x08009758 = `_malloc_r` (Ubuntu libc_a-mallocr.o placed at 0x08009710 = sbrk_aligned+_malloc_r, 90.9% bytes equal); 0x08008980 tail-calls 0x08009858 = `_free_r` (libc_a-freer.o 89.9%).'),
 ('0x0800DEFC', 'A: get_tapping_term (caller vote) / B: "waiting_buffer_scan_tap split1" and the inference TAPPING_TERM_PER_KEY off', '**A**. Body `20af 4770` = movs r0,#175; bx lr. Called from tap_dance_task@0x080120EC after building a keyrecord_t on the stack (`strd r3,r3,[sp]; mov r1,sp; ldrh r0,[active_td]; bl 0x0800DEFC; cmp r5,r0`) where ref tap_dance_task@0x080105EC has `cmp r0,#140` inline; from waiting_buffer_scan_tap@0x0800DF52 (preceded by `bl get_record_keycode` 0x0800D334) where ref has `cmp r2,#139`; and twice from process_tapping (0x0800E016, 0x0800E192). This call shape only exists with TAPPING_TERM_PER_KEY. The body sits at the action_tapping.o link position (after waiting_buffer_typed.isra.0), i.e. it is the weak default returning TAPPING_TERM = 175, not a user override. process_tapping still has `cmp r7,#174` = QUICK_TAP_TERM (= TAPPING_TERM) compared with `<`.'),
 ('0x0800DF00', 'A: unmatched / B: waiting_buffer_scan_tap split2 (148 B)', '**B** confirmed: same control flow as ref 0x0800BF3C (`cmp #15`, ring index `and #7`, `bfi #4,#4`, `bl process_record` 0x0800DAD8, tail `b.w debug_waiting_buffer` 0x0800DE58); 16 B larger because the inline TAPPING_TERM compare became two calls.'),
 ('0x0800E3B0', 'A: clear_oneshot_mods (exact) / B: clear_oneshot_locked_mods', '**B**. The body clears byte 0x200016A5 and calls 0x0800E38C. 0x200016A5 is also written by add_oneshot_locked_mods@0x0800E394 (A exact) and del_oneshot_locked_mods@0x0800E3C8; the other group (get 0x0800E380, add 0x0800E3EC, del 0x0800E408, clear 0x0800E424) uses 0x200016A6 and calls 0x0800E3E4. Orientation pinned by process_action@0x0800D83A-0x0800D846: `bl register_mods(0x0800D672); bl 0x0800E408; bl 0x0800E394` = quantum/action.c:464-466 `register_mods; del_oneshot_mods; add_oneshot_locked_mods`. Hence 0x200016A6 = oneshot_mods, 0x200016A5 = oneshot_locked_mods, 0x0800E38C = oneshot_locked_mods_changed_kb (-> user 0x0800D08C), 0x0800E3E4 = oneshot_mods_changed_kb (-> user 0x0800D088). A matched the wrong twin because ref_feat contains no clear_oneshot_locked_mods.'),
 ('0x080119F8', 'A: {default_layer_state_set|layer_state_set} ambiguous / B: leader_reset_timer', '**B**. Body `bl timer_read(0x08012574); ldr r3,=0x20002006; strh r0,[r3]`; 0x20002006 is the halfword leader_start@0x08011950-56 writes (leader_time). A already places default_layer_state_set at 0x0800DBD0 and layer_state_set at 0x0800DC24. Exists because LEADER_PER_KEY_TIMING is defined.'),
 ('0x08016304 / 0x08016340', 'A: spi_lld_serve_tx_interrupt 60 B (exact), rx 136 B; C agrees / B: swapped (opsim 0.53)', '**A**. 0x08016304 is instruction-identical to ref spi_lld_serve_tx_interrupt 0x08014824 (`tst.w r1,#12; bl chSysHalt; bl spi_lld_stop_abort.isra.0; blx r3; msr BASEPRI,#0x30; bl chThdResumeI`); ref sizes tx 60 / rx 136 match.'),
 ('0x080166EC-0x08016704', 'A: _kill 16, _getpid 4 @0x080166FC, bx-lr set @0x08016700 / B: _kill 20, _getpid @0x08016700', '**A** + link order: _kill ends with the noreturn `bl abort` so B ran it into `movs r0,#1; bx lr` (= _getpid, 4 B); the lone `bx lr` at 0x08016700 is `_fini` (ref order _exit,_kill,_getpid,_fini; B had reported _fini absent).'),
 ('0x08010E4C', 'A: rgb_matrix_toggle_eeprom_helper exact @0x08010E7C / B: merged 104-B row increase_val_helper+toggle_eeprom_helper', 'split into rgb_matrix_increase_val_helper 48 B + rgb_matrix_toggle_eeprom_helper 56 B (ref 44/56).'),
 ('0x08013CD0', 'A: stInit 4 B @0x08013CF6 / B: halInit 42 B (stInit "absent")', 'halInit is 38 B ending `ldmia.w sp!,{r3,lr}; b.w 0x08013CF6`; 0x08013CF6 `b.w 0x08016578 (st_lld_init)` = stInit.'),
 ('0x08013B34', 'A: chMtxLockS fuzzy from 0x08013B3E / B: chMtxObjectInit 12 B + chMtxLockS @0x08013B40 (opsim 1.0, C agrees)', '**B** (A start off by 2).'),
 ('0x08009344', 'A: 4-B ambiguous {_close_r|_lseek_r|null_sendchar_func|...} / lib: __fp_lock', '**lib** (findfp.o placement 0x08009344-0x08009568, 201/201 windows, 82% bytes equal).'),
 ('11 tiny A placements', "2-4 B 'bx lr'/'movs;bx lr' bodies A placed at 0x0800896E, 0x0800A1BA, 0x0800D4AE, 0x0800DBC2, 0x0800FBA8, 0x0801016A, 0x08013AF8, 0x08014894, 0x08014C76, 0x08014E34, 0x08014E38", 'dropped: each lies inside a larger function verified by B (opsim >= 0.8 or gcc13 agreement) - function tails, a literal-pool word (0x0801016A = 0x20000D07), or the two return paths of efl_lld_start_erase_sector.'),
 ('0x08008000', 'A: _crt0_entry 116 B + 7 crt0 loop labels / B: _crt0_entry 284 B', 'kept as one 284-B row (asm local labels listed in the evidence column).'),
 ('B merge labels', 'B: "oneshot_mods_changed_user+oneshot_mods_changed_kb" @0x0800E3E4, "process_leader+leader_start_user" @0x080118F4', "renamed to the kb/library function alone: the ref's 2-B user stubs are replaced by the user's real hooks at 0x0800D088 and 0x0800CDF4."),
]
md.append(tbl(['address', 'A vs B', 'resolution / evidence'], C))
md.append("\nMethod C (gcc13) disagreed with A=B only on clone naming (`spi_lld_stop_abort.isra.0` vs `spi_lld_stop_abort`, `chSchDoPreemption` vs `__sch_reschedule_ahead` alias) - same functions.\n")
md.append("## 3. Hooks (`hooks_final.json`)\n")
H = [(h['hook'], h.get('dump_addr') or '-', h.get('size') or '-', h['status'], '; '.join(h['callers'])[:160], h.get('disasm', '')) for h in hooks['hooks']]
md.append(tbl(['hook', 'dump addr', 'size', 'status', 'callers proving identity', 'disasm'], H))
md.append("\n`status`: custom = body is user code (matches no reference weak default); stock-default = the QMK weak default body at its library link position; stock-kb = Keychron/keyboard-level implementation unchanged from the fork; not-found = not in the image.\n")
td = hooks['tap_dance_actions_init_image']
md.append("### tap_dance_actions init image\n")
md.append(f"Flash {td['flash_addr']} -> RAM {td['ram_addr']} ({td['mapping']}). Words: {' '.join(td['words'])}. One 28-B entry: " + '; '.join(f"{k} = {v}" for k, v in td['decoded'].items()) + f". {td['next_object']}\n")
md.append("### encoder_map (rodata 0x080169A0, 24 B, 24 B before keymaps[])\n")
md.append('\n'.join(f"* {k}: {v}" for k, v in hooks['encoder_map']['layers'].items()) + "\n\nKeycode values from quantum/keycodes.h of the fork: KC_AUDIO_VOL_UP 0x00A9 (KC_VOLU), KC_AUDIO_VOL_DOWN 0x00AA (KC_VOLD), RGB_VAI 0x7827, RGB_VAD 0x7828. `ENCODER_CCW_CW(a,b)` stores a at index 0 (CCW) and b at index 1 (CW).\n")
md.append("### What the custom hooks do (from `disasm/`, cross-checked with the sibling source `keymaps/default/keymap.c` of the user's dactyl_manuform build - see `refs/dactyl_reference_summary.md`)\n")
md.append("""* **process_record_user** (0x0800D104, 192 B): calls `process_record_keychron_common` first (returns false -> return false). If `move_to_lower` (0x200015E8) is set and the key is not TD(0) (`cmp.w r4,#0x5700`) it is cleared. If `return_to_mouse` (0x200015E9) is set and `layer_state_is(1)` is false it is cleared. On press: `KC_CAPS` (0x39) -> reads `host_keyboard_led_state()` bit 1 (caps_lock) and stores the flag 0x200015DC; keycodes in OSM range with `(kc-0x52A2) <= 22` and bit set in mask 0x410041 -> OSM(MOD_LSFT)=0x52A2, OSM(MOD_LGUI)=0x52A8, OSM(MOD_RSFT)=0x52B2, OSM(MOD_RGUI)=0x52B8 -> tail-call `check_unlock_osm` (0x0800D0B4); `QK_USER_0` (0x7E40) -> register/unregister KC_DOT (0x37) then KC_SLSH (0x38) = types `./` and returns false; `QK_USER_1` (0x7E41) -> KC_DOT then falls into the QK_USER_0 block = `../`, returns false. Everything else returns true.
* **check_unlock_osm / find_osm_slot** (0x0800D0B4 / 0x0800D090): `find_osm_slot(kc)` loads `held_osm[0]` (0x200015E0), compares `*p` and `*(uint16_t*)((char*)p+4)` with kc (the source's `index += sizeof(uint16_t)` on a `uint16_t*`, i.e. +4 bytes) and returns the matching pointer, else NULL (when `held_osm[0]` is NULL the compiled code reads address 0x00000004 - the vector-table word 0x0800811D - and never matches; harmless UB inherited from the source). `check_unlock_osm`: no slot -> return true (key processed normally); `get_mods()==0` -> return false; `*slot == kc` -> return false (always true when a slot was found, so the following block is dead in this build); otherwise clear_oneshot_mods, clear_oneshot_locked_mods, unregister_mods(get_oneshot_mods()), held_osm[0..1]=NULL, shift_active=gui_active=0, return false. Net effect in this build: the four OSM keys are always passed through (return true) because `held_osm` is never written anywhere in the image (both words only ever zeroed).
* **handle_oneshots** (0x0800D010, tail-called by both `oneshot_mods_changed_user` 0x0800D088 and `oneshot_locked_mods_changed_user` 0x0800D08C): shift = mods & 0x22, gui = mods & 0x88. If shift and !shift_active -> `rgb_matrix_set_color_all(255,255,255)`, shift_active=1; if !shift and shift_active -> set_color_all(0,0,0), shift_active=0; if gui and !gui_active -> set_color_all(255,255,0), gui_active=1; if !gui and gui_active -> set_color_all(0,0,0), gui_active=0.
* **rgb_matrix_indicators_advanced_user** (0x0800CF74): for each LED led_min..led_max: layer = `biton16(layer_state | default_layer_state)` (0x2000162E | 0x20001630); `tbb` on layer: 1 -> (0,255,0), 2 -> (0,0,255), 3 -> (255,128,0), 4 -> (0,128,128), 5 -> (255,0,0) via `rgb_matrix_set_color`; layer 0 -> nothing. Then if gui_active -> (255,255,0) on that LED; else if shift_active || caps flag -> (255,255,255). Returns false.
* **TD(0)** (`td0_on_dance_finished` 0x0800D1EC, `cur_dance` 0x0800D1C4 returning TD_UNKNOWN=1/TD_SINGLE_TAP=2/TD_SINGLE_HOLD=3/TD_DOUBLE_TAP=4 exactly as the source enum, `td0_on_reset` = empty): HOLD -> `layer_clear(); layer_move(4)`; DOUBLE_TAP -> `layer_clear(); layer_move(1)`; SINGLE_TAP -> if `layer_state_is(4)`: return_to_mouse=1, layer_clear, `layer_oneshot_Lower()` (0x0800CDDA: layer_on(1); set_oneshot_layer(1, ONESHOT_START); clear_oneshot_layer_state(ONESHOT_PRESSED)); elif move_to_lower: layer_clear; layer_move(1); move_to_lower=0; elif `layer_state_is(1)`: layer_clear + layer_oneshot_Lower; else move_to_lower=1 + layer_oneshot_Lower. `oneshot_layer_changed_user` (0x0800D25C): when the oneshot layer ends (layer==0) and return_to_mouse: layer_clear; layer_move(4); return_to_mouse=0. (In the sibling source layer 1 = _LOWER and layer 4 = _MOUSE.)
* **leader_start_user** (0x0800CDF4): `rgb_matrix_set_color_all(255,0,255)`. **leader_end_user** (0x0800CDFE): `rgb_matrix_set_color_all(0,0,0)`, then `if/else if` chain: F -> LGUI+P, LGUI+K; (A,Q) -> LCTL+A, Z, Q, ENTER; Y -> LCTL+X, Y, ENTER; (LCTL,I) -> LCTL+LALT+I; J -> LGUI+P; F -> LGUI+QUOTE (dead: shadowed by the first F test; the sibling source has S/H/C/R entries there); DEL -> LGUI+UP, LEFT. All with register_code/unregister_code pairs (no tap_code16/SEND_STRING in the image).
* **keyboard_post_init_user** (0x0800CF60): `default_layer_set(0); rgb_matrix_mode(16)`; mode 16 = RGB_MATRIX_TYPING_HEATMAP (rgb_task_render@0x08010A8A `cmp r6,#22; tbb`, case 16 @0x08010BF4 -> `bl TYPING_HEATMAP` 0x08010920; the 22 enabled effects are exactly `info.json` `rgb_matrix.animations` of the fork: 1 SOLID_COLOR, 2 BREATHING, 3 BAND_SPIRAL_VAL, 4 CYCLE_ALL, 5 CYCLE_LEFT_RIGHT, 6 CYCLE_UP_DOWN, 7 RAINBOW_MOVING_CHEVRON, 8 CYCLE_OUT_IN, 9 CYCLE_OUT_IN_DUAL, 10 CYCLE_PINWHEEL, 11 CYCLE_SPIRAL, 12 DUAL_BEACON, 13 RAINBOW_BEACON, 14 JELLYBEAN_RAINDROPS, 15 PIXEL_RAIN (inlined), 16 TYPING_HEATMAP, 17 DIGITAL_RAIN, 18 SOLID_REACTIVE_SIMPLE, 19 SOLID_REACTIVE_MULTIWIDE, 20 SOLID_REACTIVE_MULTINEXUS, 21 SPLASH, 22 SOLID_SPLASH).
""")
md.append("### User statics (.bss, no init image)\n")
md.append(tbl(['RAM', 'meaning'], [(k, v) for k, v in hooks['user_statics_bss'].items()]))
md.append("\nOther RAM cells used by the hooks: 0x2000162E layer_state, 0x20001630 default_layer_state, 0x200016A5 oneshot_locked_mods, 0x200016A6 oneshot_mods, 0x20000E7C tap_dance_actions, 0x20002006 leader_time, 0x20002008 leading.\n")
md.append("## 4. Custom / not-explained-by-reference code regions (final)\n")
R = [
 ('0x0800CDD8', 1188, 'USER keymap.c code (15 functions): td0_on_reset 2, layer_oneshot_Lower 26, leader_start_user 10, leader_end_user 354, keyboard_post_init_user 20, rgb_matrix_indicators_advanced_user 156, handle_oneshots 120, oneshot_mods_changed_user 4, oneshot_locked_mods_changed_user 4, find_osm_slot 36, check_unlock_osm 80, process_record_user 192, cur_dance 40, td0_on_dance_finished 112, oneshot_layer_changed_user 32 (0x0800CDD8-0x0800D27C). Both methods, all callers/pointers verified.'),
 ('0x0800D27C', 80, 'keymap_introspection.c compiled from the user TU: keycode_at_keymap_location_raw 40 (literal keymaps 0x080169B8, 6x6x18), thunk 4, keycode_at_encodermap_location_raw 32 (literal encoder_map 0x080169A0), thunk 4. Stock code, user constants.'),
 ('0x0800DC3C', 28, 'layer_state_is (action_layer.c) - library function absent from the reference builds (nothing calls it there), kept alive by the user code.'),
 ('0x0800E3B0', 24, 'clear_oneshot_locked_mods (action_util.c) - absent from ref_feat, called from check_unlock_osm.'),
 ('0x080119F8', 16, 'leader_reset_timer (leader.c) - present because LEADER_PER_KEY_TIMING is defined; called from process_leader@0x080118F4.'),
 ('0x0800DEFC', 4, 'get_tapping_term weak default (movs r0,#175) - present because TAPPING_TERM_PER_KEY is defined (below the 16-B threshold, listed for completeness).'),
 ('0x08008448', 7544, 'libc cluster in plain *(.text): Ubuntu/Debian libnewlib-arm-none-eabi 4.4.0.20231231-2 libc_nano.a members (rand, assert, itoa, abort, utoa, strlen, memset, memcpy, malloc, fprintf, memcmp, nano-vfprintf, wbuf, fvwrite, signal, findfp, fflush, mallocr, freer, memmove, fwalk, memchr, wsetup, reallocr, nano-vfprintf_i, mlock, makebuf, stdio, msizer, signalr) - fully named in functions_final.csv; not user code.'),
 ('0x080169A0', 24, 'encoder_map[6][1][2] rodata (user table).'),
 ('0x080169B8', 1296, 'keymaps[6][6][18] rodata (user table; byte-identical to refs/ref_feat_keymap).'),
 ('0x080179C8', 28, 'tap_dance_actions[1] .data init image (user table): {0,0, NULL, 0x0800D1ED, 0x0800CDD9, NULL, NULL}.'),
]
md.append(tbl(['start', 'size', 'what it is'], R))
md.append("\nNo other unexplained code: every remaining `.text` function is a stock QMK/ChibiOS/Keychron function (A exact/fuzzy, B alignment, or both) or the padding listed in section 1.\n")
md.append("## 5. libc cluster (0x08008448-0x0800A1C0)\n")
L = []
for m in sorted(lib, key=lambda m: m['start']):
    if m['member'] in ('libc_a-fscanf.o', 'libc_a-fwscanf.o', 'libc_a-random.o', 'libc_a-dprintf.o', 'libc_a-fwprintf.o', 'libc_a-fflush_u.o', 'libc_a-fstatr.o', 'libc_a-getentropyr.o', 'libc_a-gettimeofdayr.o', 'libc_a-linkr.o', 'libc_a-mkdirr.o', 'libc_a-statr.o'): continue
    L.append((f"0x{0x08000000+m['start']:08X}", m['text_len'], m['member'], f"{m['eq']*100:.1f}%", f"{m['hits']}/{m['windows']}", ', '.join(s[2] for s in m['syms']) or 'memchr'))
L += [('0x080085E8', 16, 'libc_a-abort.o (B: opsim 0.91 vs gcc15 ref)', '50% (2 BL relocs)', '-', 'abort'), ('0x08008970', 32, 'libc_a-malloc.o', '65.6% (2 b.w + 2 literals)', '-', 'malloc, free'), ('0x08009BC4', 100, 'libc_a-reallocr.o', '85.0%', '2 (windows)', '_realloc_r'), ('0x08009FD0', 8, 'libc_a-mlock.o', '100%', '-', '__malloc_lock, __malloc_unlock (bl from _malloc_r@0x08009778/0x080097BE, _free_r@0x0800986C/0x08009842)'), ('0x0800A180', 16, 'libc_a-msizer.o', '100%', '-', '_malloc_usable_size_r (bl from _realloc_r@0x08009BD2)')]
L.sort()
md.append(tbl(['start', '.text B', 'member', 'bytes equal', 'window hits', 'symbols'], L))
md.append("\nAlias members with identical code were dropped in favour of the one the callers need (rand over random, fprintf/fiprintf over dprintf/fwprintf because `__assert_func` calls fiprintf, fflush over fflush_unlocked, signalr over the six generic `_xxx_r` syscall wrappers because the tail `b.w 0x080166FC` is `_getpid_r -> _getpid`). Method B's reading 'full newlib' was half right: it is Debian's *nano* newlib, which is built without `-ffunction-sections` (hence one contiguous plain `.text` blob pulled in archive order) and with the optimized assembly memcpy/memset/strlen/memchr/memmove.\n")
md.append("## 6. Config inferences (all from dump bytes)\n")
md.append('\n'.join(f"* **{k}**: {v}" for k, v in hooks['config_inferences'].items()))
md.append("\n\nThese agree with the user's sibling dactyl keymap config (`TAPPING_TERM 150` + `TAPPING_TERM_PER_KEY`, `ONESHOT_TAP_TOGGLE 2`, `LEADER_PER_KEY_TIMING`, `LEADER_TIMEOUT 600`, `ONESHOT_TIMEOUT` commented out) except the numeric TAPPING_TERM (175 here) and LEADER_TIMEOUT (525 here). `refs/ref_feat_keymap/config.h` should be changed to `TAPPING_TERM 175`, add `TAPPING_TERM_PER_KEY`, `LEADER_PER_KEY_TIMING`, `LEADER_TIMEOUT 525`, and drop `ONESHOT_TIMEOUT`.\n")
md.append("## 7. LTO verdict: NOT an LTO build (both methods agree; re-checked)\n")
md.append("""* Weak defaults survive as separate 2/4-B functions reached by `bl`: housekeeping_task_user 0x0800E768 (`bx lr`, bl from housekeeping_task@0x0800E770), matrix_scan_user 0x0800ED16, layer_state_set_user 0x0800DC18, default_layer_state_set_user 0x0800DBC4, keyboard_pre_init_user 0x0800E732, rgb_matrix_indicators_user 0x0801017A, eeconfig_init_user 0x0800E61E, get_tapping_term 0x0800DEFC; 4-B tail-call thunks exist (housekeeping_task_kb 0x0800C714 `b.w keychron_task`, keycode_at_keymap_location 0x0800D2A4, stInit 0x08013CF6). LTO inlines all of these.
* Per-TU compiler clones are present (`waiting_buffer_typed.isra.0` 0x0800DEB8, `jellybean_raindrops_set_color.isra.0` 0x0800FE8C, `spi_lld_stop_abort.isra.0` 0x0801625C, `otg_epout_handler.constprop.0`), and 817/817 consecutive matched functions keep the reference's per-object link order over 101 objects (Method B).
* Method A: 21036 B exact vs the three non-LTO refs against 4838 B vs the three LTO refs (same 4x ratio as the known non-LTO Keychron stock build: 26.1% vs 7.5%).
* Size distribution: 931 detected functions, median 32 B (non-LTO ref: 915 sections, median 32; LTO ref: 407 sections, median 52). Image 98052 B > non-LTO ref_feat 95280 B >> LTO 88168 B; the surplus is the 3.9 KB larger Debian libc plus 1 KB user code.
""")
md.append("## 8. Compiler guess (reconciled)\n")
md.append("""**Debian/Ubuntu packaged Arm toolchain: `gcc-arm-none-eabi` 13.2.rel1 (GCC 13.2.1 20231009) with `libnewlib-arm-none-eabi` 4.4.0.20231231-2 - i.e. `apt install gcc-arm-none-eabi` on Ubuntu 24.04 (noble) / Debian testing in mid-2024.** Evidence, strongest first:

1. The newlib `__FILE__` string in the dump, `../../../../../../newlib/libc/stdlib/rand.c` @0x08017674, is exactly the string inside Ubuntu noble's `libnewlib-arm-none-eabi_4.4.0.20231231-2_all.deb` `libc_nano.a` (`compare_images.md`, `refs/toolchain_debs_SOURCES.txt`); the jammy 3.3.0 package has 8 levels, Arm GNU / xPack / crosstool-NG builds have absolute paths.
2. 30 members of that `libc_nano.a` are byte-identical to the dump modulo relocations (section 5: strlen/memset/memcpy/memcmp/memmove/memchr/fwalk 100%, _printf_i 98.8%, ...) and account for the whole 7544-B libc cluster; the gcc-15.2 QMK toolchain's newlib-nano matched 1 member (160 B) and jammy's 3 members.
3. libgcc: the 700-B `__udivmoddi4` at 0x08008188 matched the Ubuntu noble `gcc-arm-none-eabi_13.2.rel1-2` `libgcc.a` member (`lib_match.md`: 1 member, 700 B) and neither the 14.2.rel1 nor the gcc-15.2 libgcc (684 B there).
4. Same-source rebuild with xPack GCC 13.2.1 (`refs/ref1011_feat_gcc13.elf`, the same GCC 13.2.1 20231009 code generator as Arm's 13.2.Rel1 that Debian packages): `tools/match_ref_funcs.py` finds 507 exact masked functions / 31432 B in the dump, versus 356 / 17278 B for the gcc-15.2 build of the same sources (the ~500 B of TD/leader code present only in the feat keymap cannot explain a 14 KB difference). Method B's opcode similarity (dump vs gcc-15: mean 0.920) is consistent with a neighbouring GCC major.
5. Method A's rate vs gcc-15 (32% exact, above the GCC-10 stock build's 26%, far below same-compiler 90%) and Method B's 'GCC 13/14, in-tree build dir, non-function-sectioned nano libs' both point the same way; B's specific 'Homebrew formula' hypothesis is superseded by the Debian evidence (Homebrew's newlib is not built with the Debian relative path).

Not verified: the exact Debian package revision (13.2.rel1-2 vs -1) and whether the build ran on Ubuntu or Debian - both ship the same upstream 13.2.rel1 tarball. A rebuild of ref_feat with that toolchain (available as the two .debs listed in `refs/toolchain_debs_SOURCES.txt`) should reproduce the dump's code section byte-for-byte except for the keymap.c differences.
""")
md.append("## 9. Open questions\n")
md.append("""* `held_osm[]` is never written in the image, so `check_unlock_osm` always returns true for the four OSM keys; if the recovered keymap.c is meant to reproduce behaviour exactly, reproducing this dead logic is optional. The source's `slot = &keycode` is the same no-op.
* The second `leader_sequence_one_key(KC_F)` branch (LGUI+QUOTE) is unreachable; the sibling source has S/H/C/R sequences in that position - the 2024 firmware simply had two F entries.
* LEADER_TIMEOUT 525 rests on a single `movw #0x20D` in leader_sequence_timed_out (Method B); TAPPING_TERM 175 rests on `movs r0,#175` in get_tapping_term plus `cmp r7,#174` in process_tapping (two independent sites).
* 1188 B of user code vs the 244-B ref placeholder means the source keymap.c needs the functions listed in section 3; the recovered keymaps[] table, encoder_map and tap_dance_actions are exact.
* Anonymous rodata/.data (about 2.3 KB: strings, USB descriptors, ChibiOS config structs, `.data` init images of stock objects) is unnamed but stock; the 34 named data objects are in `functions_final.csv` with status `data`.
""")
open(BK + 'ANALYSIS_functions.md', 'w').write('\n'.join(md))
print('written', len('\n'.join(md)), 'chars')
