// Generated by build_data.py -- do not edit by hand.
window.KEYMAP_DATA = {
 "meta": {
  "keyboard": "handwired/dactyl_manuform/5x6",
  "keymap": "default",
  "sourceCommit": "1fa3e5ddc2",
  "generatedBy": "build_data.py"
 },
 "geometry": [
  {
   "matrix": [
    0,
    0
   ],
   "x": 0,
   "y": 0,
   "half": "left"
  },
  {
   "matrix": [
    0,
    1
   ],
   "x": 1,
   "y": 0,
   "half": "left"
  },
  {
   "matrix": [
    0,
    2
   ],
   "x": 2,
   "y": 0,
   "half": "left"
  },
  {
   "matrix": [
    0,
    3
   ],
   "x": 3,
   "y": 0,
   "half": "left"
  },
  {
   "matrix": [
    0,
    4
   ],
   "x": 4,
   "y": 0,
   "half": "left"
  },
  {
   "matrix": [
    0,
    5
   ],
   "x": 5,
   "y": 0,
   "half": "left"
  },
  {
   "matrix": [
    6,
    0
   ],
   "x": 11,
   "y": 0,
   "half": "right"
  },
  {
   "matrix": [
    6,
    1
   ],
   "x": 12,
   "y": 0,
   "half": "right"
  },
  {
   "matrix": [
    6,
    2
   ],
   "x": 13,
   "y": 0,
   "half": "right"
  },
  {
   "matrix": [
    6,
    3
   ],
   "x": 14,
   "y": 0,
   "half": "right"
  },
  {
   "matrix": [
    6,
    4
   ],
   "x": 15,
   "y": 0,
   "half": "right"
  },
  {
   "matrix": [
    6,
    5
   ],
   "x": 16,
   "y": 0,
   "half": "right"
  },
  {
   "matrix": [
    1,
    0
   ],
   "x": 0,
   "y": 1,
   "half": "left"
  },
  {
   "matrix": [
    1,
    1
   ],
   "x": 1,
   "y": 1,
   "half": "left"
  },
  {
   "matrix": [
    1,
    2
   ],
   "x": 2,
   "y": 1,
   "half": "left"
  },
  {
   "matrix": [
    1,
    3
   ],
   "x": 3,
   "y": 1,
   "half": "left"
  },
  {
   "matrix": [
    1,
    4
   ],
   "x": 4,
   "y": 1,
   "half": "left"
  },
  {
   "matrix": [
    1,
    5
   ],
   "x": 5,
   "y": 1,
   "half": "left"
  },
  {
   "matrix": [
    7,
    0
   ],
   "x": 11,
   "y": 1,
   "half": "right"
  },
  {
   "matrix": [
    7,
    1
   ],
   "x": 12,
   "y": 1,
   "half": "right"
  },
  {
   "matrix": [
    7,
    2
   ],
   "x": 13,
   "y": 1,
   "half": "right"
  },
  {
   "matrix": [
    7,
    3
   ],
   "x": 14,
   "y": 1,
   "half": "right"
  },
  {
   "matrix": [
    7,
    4
   ],
   "x": 15,
   "y": 1,
   "half": "right"
  },
  {
   "matrix": [
    7,
    5
   ],
   "x": 16,
   "y": 1,
   "half": "right"
  },
  {
   "matrix": [
    2,
    0
   ],
   "x": 0,
   "y": 2,
   "half": "left"
  },
  {
   "matrix": [
    2,
    1
   ],
   "x": 1,
   "y": 2,
   "half": "left"
  },
  {
   "matrix": [
    2,
    2
   ],
   "x": 2,
   "y": 2,
   "half": "left"
  },
  {
   "matrix": [
    2,
    3
   ],
   "x": 3,
   "y": 2,
   "half": "left"
  },
  {
   "matrix": [
    2,
    4
   ],
   "x": 4,
   "y": 2,
   "half": "left"
  },
  {
   "matrix": [
    2,
    5
   ],
   "x": 5,
   "y": 2,
   "half": "left"
  },
  {
   "matrix": [
    8,
    0
   ],
   "x": 11,
   "y": 2,
   "half": "right"
  },
  {
   "matrix": [
    8,
    1
   ],
   "x": 12,
   "y": 2,
   "half": "right"
  },
  {
   "matrix": [
    8,
    2
   ],
   "x": 13,
   "y": 2,
   "half": "right"
  },
  {
   "matrix": [
    8,
    3
   ],
   "x": 14,
   "y": 2,
   "half": "right"
  },
  {
   "matrix": [
    8,
    4
   ],
   "x": 15,
   "y": 2,
   "half": "right"
  },
  {
   "matrix": [
    8,
    5
   ],
   "x": 16,
   "y": 2,
   "half": "right"
  },
  {
   "matrix": [
    3,
    0
   ],
   "x": 0,
   "y": 3,
   "half": "left"
  },
  {
   "matrix": [
    3,
    1
   ],
   "x": 1,
   "y": 3,
   "half": "left"
  },
  {
   "matrix": [
    3,
    2
   ],
   "x": 2,
   "y": 3,
   "half": "left"
  },
  {
   "matrix": [
    3,
    3
   ],
   "x": 3,
   "y": 3,
   "half": "left"
  },
  {
   "matrix": [
    3,
    4
   ],
   "x": 4,
   "y": 3,
   "half": "left"
  },
  {
   "matrix": [
    3,
    5
   ],
   "x": 5,
   "y": 3,
   "half": "left"
  },
  {
   "matrix": [
    9,
    0
   ],
   "x": 11,
   "y": 3,
   "half": "right"
  },
  {
   "matrix": [
    9,
    1
   ],
   "x": 12,
   "y": 3,
   "half": "right"
  },
  {
   "matrix": [
    9,
    2
   ],
   "x": 13,
   "y": 3,
   "half": "right"
  },
  {
   "matrix": [
    9,
    3
   ],
   "x": 14,
   "y": 3,
   "half": "right"
  },
  {
   "matrix": [
    9,
    4
   ],
   "x": 15,
   "y": 3,
   "half": "right"
  },
  {
   "matrix": [
    9,
    5
   ],
   "x": 16,
   "y": 3,
   "half": "right"
  },
  {
   "matrix": [
    4,
    2
   ],
   "x": 2,
   "y": 4,
   "half": "left"
  },
  {
   "matrix": [
    4,
    3
   ],
   "x": 3,
   "y": 4,
   "half": "left"
  },
  {
   "matrix": [
    10,
    2
   ],
   "x": 13,
   "y": 4,
   "half": "right"
  },
  {
   "matrix": [
    10,
    3
   ],
   "x": 14,
   "y": 4,
   "half": "right"
  },
  {
   "matrix": [
    4,
    4
   ],
   "x": 4,
   "y": 5,
   "half": "left"
  },
  {
   "matrix": [
    4,
    5
   ],
   "x": 5,
   "y": 5,
   "half": "left"
  },
  {
   "matrix": [
    10,
    0
   ],
   "x": 11,
   "y": 5,
   "half": "right"
  },
  {
   "matrix": [
    10,
    1
   ],
   "x": 12,
   "y": 5,
   "half": "right"
  },
  {
   "matrix": [
    5,
    4
   ],
   "x": 6,
   "y": 6,
   "half": "left"
  },
  {
   "matrix": [
    5,
    5
   ],
   "x": 7,
   "y": 6,
   "half": "left"
  },
  {
   "matrix": [
    11,
    0
   ],
   "x": 9,
   "y": 6,
   "half": "right"
  },
  {
   "matrix": [
    11,
    1
   ],
   "x": 10,
   "y": 6,
   "half": "right"
  },
  {
   "matrix": [
    5,
    3
   ],
   "x": 6,
   "y": 7,
   "half": "left"
  },
  {
   "matrix": [
    5,
    2
   ],
   "x": 7,
   "y": 7,
   "half": "left"
  },
  {
   "matrix": [
    11,
    3
   ],
   "x": 9,
   "y": 7,
   "half": "right"
  },
  {
   "matrix": [
    11,
    2
   ],
   "x": 10,
   "y": 7,
   "half": "right"
  }
 ],
 "layers": [
  {
   "index": 0,
   "name": "_QWERTY",
   "phantom": false,
   "rgb": null,
   "keys": [
    {
     "raw": "KC_ESC",
     "label": "Esc",
     "kind": "basic"
    },
    {
     "raw": "KC_1",
     "label": "1",
     "kind": "basic"
    },
    {
     "raw": "KC_2",
     "label": "2",
     "kind": "basic"
    },
    {
     "raw": "KC_3",
     "label": "3",
     "kind": "basic"
    },
    {
     "raw": "KC_4",
     "label": "4",
     "kind": "basic"
    },
    {
     "raw": "KC_5",
     "label": "5",
     "kind": "basic"
    },
    {
     "raw": "KC_6",
     "label": "6",
     "kind": "basic"
    },
    {
     "raw": "KC_7",
     "label": "7",
     "kind": "basic"
    },
    {
     "raw": "KC_8",
     "label": "8",
     "kind": "basic"
    },
    {
     "raw": "KC_9",
     "label": "9",
     "kind": "basic"
    },
    {
     "raw": "KC_0",
     "label": "0",
     "kind": "basic"
    },
    {
     "raw": "KC_BSLS",
     "label": "\\",
     "kind": "basic"
    },
    {
     "raw": "KC_GRV",
     "label": "`",
     "kind": "basic"
    },
    {
     "raw": "TD(TD_Q_TILD)",
     "label": "Q",
     "kind": "tapdance",
     "td": "TD_Q_TILD"
    },
    {
     "raw": "KC_W",
     "label": "W",
     "kind": "basic"
    },
    {
     "raw": "KC_E",
     "label": "E",
     "kind": "basic"
    },
    {
     "raw": "KC_R",
     "label": "R",
     "kind": "basic"
    },
    {
     "raw": "KC_T",
     "label": "T",
     "kind": "basic"
    },
    {
     "raw": "KC_Y",
     "label": "Y",
     "kind": "basic"
    },
    {
     "raw": "KC_U",
     "label": "U",
     "kind": "basic"
    },
    {
     "raw": "KC_I",
     "label": "I",
     "kind": "basic"
    },
    {
     "raw": "KC_O",
     "label": "O",
     "kind": "basic"
    },
    {
     "raw": "KC_P",
     "label": "P",
     "kind": "basic"
    },
    {
     "raw": "KC_MINS",
     "label": "-",
     "kind": "basic"
    },
    {
     "raw": "OSM(MOD_LSFT)",
     "label": "one-shot Shift",
     "kind": "oneshot_mod",
     "mod": "MOD_LSFT"
    },
    {
     "raw": "KC_A",
     "label": "A",
     "kind": "basic"
    },
    {
     "raw": "TD(TD_S_OSM)",
     "label": "S",
     "kind": "tapdance",
     "td": "TD_S_OSM"
    },
    {
     "raw": "TD(TD_D_OSM)",
     "label": "D",
     "kind": "tapdance",
     "td": "TD_D_OSM"
    },
    {
     "raw": "TD(LAYR_DOWN)",
     "label": "F",
     "kind": "tapdance",
     "td": "LAYR_DOWN"
    },
    {
     "raw": "TD(TD_G_CAPS)",
     "label": "G",
     "kind": "tapdance",
     "td": "TD_G_CAPS"
    },
    {
     "raw": "TD(TD_H_CAPS)",
     "label": "H",
     "kind": "tapdance",
     "td": "TD_H_CAPS"
    },
    {
     "raw": "TD(TD_J_OSM)",
     "label": "J",
     "kind": "tapdance",
     "td": "TD_J_OSM"
    },
    {
     "raw": "TD(LAYR_UP)",
     "label": "K",
     "kind": "tapdance",
     "td": "LAYR_UP"
    },
    {
     "raw": "KC_L",
     "label": "L",
     "kind": "basic"
    },
    {
     "raw": "KC_QUOT",
     "label": "'",
     "kind": "basic"
    },
    {
     "raw": "OSM(MOD_RSFT)",
     "label": "one-shot Shift",
     "kind": "oneshot_mod",
     "mod": "MOD_RSFT"
    },
    {
     "raw": "KC_TAB",
     "label": "Tab",
     "kind": "basic"
    },
    {
     "raw": "TD(TD_Z_GRV)",
     "label": "Z",
     "kind": "tapdance",
     "td": "TD_Z_GRV"
    },
    {
     "raw": "KC_X",
     "label": "X",
     "kind": "basic"
    },
    {
     "raw": "KC_C",
     "label": "C",
     "kind": "basic"
    },
    {
     "raw": "TD(TD_V_TAB)",
     "label": "V",
     "kind": "tapdance",
     "td": "TD_V_TAB"
    },
    {
     "raw": "KC_B",
     "label": "B",
     "kind": "basic"
    },
    {
     "raw": "KC_N",
     "label": "N",
     "kind": "basic"
    },
    {
     "raw": "KC_M",
     "label": "M",
     "kind": "basic"
    },
    {
     "raw": "KC_COMM",
     "label": ",",
     "kind": "basic"
    },
    {
     "raw": "KC_DOT",
     "label": ".",
     "kind": "basic"
    },
    {
     "raw": "KC_SLSH",
     "label": "/",
     "kind": "basic"
    },
    {
     "raw": "KC_SCLN",
     "label": ";",
     "kind": "basic"
    },
    {
     "raw": "KC_HOME",
     "label": "Home",
     "kind": "basic"
    },
    {
     "raw": "KC_END",
     "label": "End",
     "kind": "basic"
    },
    {
     "raw": "KC_PGUP",
     "label": "PgUp",
     "kind": "basic"
    },
    {
     "raw": "KC_PGDN",
     "label": "PgDn",
     "kind": "basic"
    },
    {
     "raw": "KC_SPC",
     "label": "Space",
     "kind": "basic"
    },
    {
     "raw": "KC_BSPC",
     "label": "Bksp",
     "kind": "basic"
    },
    {
     "raw": "KC_DEL",
     "label": "Del",
     "kind": "basic"
    },
    {
     "raw": "KC_ENT",
     "label": "Enter",
     "kind": "basic"
    },
    {
     "raw": "KC_ESC",
     "label": "Esc",
     "kind": "basic"
    },
    {
     "raw": "OSL(_LEADR)",
     "label": "OSL _LEADR",
     "kind": "oneshot_layer",
     "layer": "_LEADR"
    },
    {
     "raw": "KC_DEL",
     "label": "Del",
     "kind": "basic"
    },
    {
     "raw": "KC_LALT",
     "label": "LAlt",
     "kind": "basic"
    },
    {
     "raw": "KC_LCTL",
     "label": "LCtrl",
     "kind": "basic"
    },
    {
     "raw": "KC_CAPS",
     "label": "Caps",
     "kind": "basic"
    },
    {
     "raw": "KC_CAPS",
     "label": "Caps",
     "kind": "basic"
    },
    {
     "raw": "OSL(_LEADR)",
     "label": "OSL _LEADR",
     "kind": "oneshot_layer",
     "layer": "_LEADR"
    }
   ]
  },
  {
   "index": 1,
   "name": "_LOWER",
   "phantom": false,
   "rgb": "#00ff00",
   "keys": [
    {
     "raw": "KC_BSPC",
     "label": "Bksp",
     "kind": "basic"
    },
    {
     "raw": "LCTL(KC_1)",
     "label": "Ctrl+1",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_2)",
     "label": "Ctrl+2",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_TAB)",
     "label": "Ctrl+Tab",
     "kind": "chord"
    },
    {
     "raw": "LCTL(LSFT(KC_TAB))",
     "label": "Ctrl+Shift+Tab",
     "kind": "chord"
    },
    {
     "raw": "LSFT(KC_TAB)",
     "label": "Shift+Tab",
     "kind": "chord"
    },
    {
     "raw": "LALT(KC_ENT)",
     "label": "Alt+Enter",
     "kind": "chord"
    },
    {
     "raw": "LALT(KC_LEFT)",
     "label": "Alt+\u2190",
     "kind": "chord"
    },
    {
     "raw": "LALT(KC_RGHT)",
     "label": "Alt+\u2192",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_TAB)",
     "label": "Ctrl+Tab",
     "kind": "chord"
    },
    {
     "raw": "KC_DEL",
     "label": "Del",
     "kind": "basic"
    },
    {
     "raw": "KC_PGUP",
     "label": "PgUp",
     "kind": "basic"
    },
    {
     "raw": "LALT(KC_GRV)",
     "label": "Alt+`",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_Q)",
     "label": "Ctrl+Q",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_W)",
     "label": "Ctrl+W",
     "kind": "chord"
    },
    {
     "raw": "KC_LALT",
     "label": "LAlt",
     "kind": "basic"
    },
    {
     "raw": "LCTL(KC_R)",
     "label": "Ctrl+R",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_T)",
     "label": "Ctrl+T",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_Y)",
     "label": "Ctrl+Y",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_U)",
     "label": "Ctrl+U",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_I)",
     "label": "Ctrl+I",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_O)",
     "label": "Ctrl+O",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_P)",
     "label": "Ctrl+P",
     "kind": "chord"
    },
    {
     "raw": "KC_HOME",
     "label": "Home",
     "kind": "basic"
    },
    {
     "raw": "LALT(KC_TAB)",
     "label": "Alt+Tab",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_A)",
     "label": "Ctrl+A",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_S)",
     "label": "Ctrl+S",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_D)",
     "label": "Ctrl+D",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_F)",
     "label": "Ctrl+F",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_0)",
     "label": "Ctrl+0",
     "kind": "chord"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "KC_UP",
     "label": "\u2191",
     "kind": "basic"
    },
    {
     "raw": "KC_LEFT",
     "label": "\u2190",
     "kind": "basic"
    },
    {
     "raw": "KC_DOWN",
     "label": "\u2193",
     "kind": "basic"
    },
    {
     "raw": "KC_RGHT",
     "label": "\u2192",
     "kind": "basic"
    },
    {
     "raw": "KC_END",
     "label": "End",
     "kind": "basic"
    },
    {
     "raw": "LSFT(KC_TAB)",
     "label": "Shift+Tab",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_Z)",
     "label": "Ctrl+Z",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_X)",
     "label": "Ctrl+X",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_C)",
     "label": "Ctrl+C",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_V)",
     "label": "Ctrl+V",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_B)",
     "label": "Ctrl+B",
     "kind": "chord"
    },
    {
     "raw": "LCTL(KC_N)",
     "label": "Ctrl+N",
     "kind": "chord"
    },
    {
     "raw": "DBL_DASH",
     "label": "--",
     "kind": "custom",
     "detail": "types --"
    },
    {
     "raw": "DOT_SLS",
     "label": "./",
     "kind": "custom",
     "detail": "types ./"
    },
    {
     "raw": "DIR_UP",
     "label": "../",
     "kind": "custom",
     "detail": "types ../"
    },
    {
     "raw": "LCTL(KC_SLSH)",
     "label": "Ctrl+/",
     "kind": "chord"
    },
    {
     "raw": "KC_PGDN",
     "label": "PgDn",
     "kind": "basic"
    },
    {
     "raw": "KC_HOME",
     "label": "Home",
     "kind": "basic"
    },
    {
     "raw": "KC_END",
     "label": "End",
     "kind": "basic"
    },
    {
     "raw": "KC_PGUP",
     "label": "PgUp",
     "kind": "basic"
    },
    {
     "raw": "KC_PGDN",
     "label": "PgDn",
     "kind": "basic"
    },
    {
     "raw": "KC_LCTL",
     "label": "LCtrl",
     "kind": "basic"
    },
    {
     "raw": "KC_LSFT",
     "label": "LShift",
     "kind": "basic"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "KC_ENT",
     "label": "Enter",
     "kind": "basic"
    },
    {
     "raw": "KC_SPC",
     "label": "Space",
     "kind": "basic"
    },
    {
     "raw": "KC_BSPC",
     "label": "Bksp",
     "kind": "basic"
    },
    {
     "raw": "KC_DEL",
     "label": "Del",
     "kind": "basic"
    },
    {
     "raw": "KC_LALT",
     "label": "LAlt",
     "kind": "basic"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "OSL(_LEADR)",
     "label": "OSL _LEADR",
     "kind": "oneshot_layer",
     "layer": "_LEADR"
    },
    {
     "raw": "KC_LCTL",
     "label": "LCtrl",
     "kind": "basic"
    },
    {
     "raw": "OSL(_LEADR)",
     "label": "OSL _LEADR",
     "kind": "oneshot_layer",
     "layer": "_LEADR"
    }
   ]
  },
  {
   "index": 2,
   "name": "_RAISE",
   "phantom": false,
   "rgb": "#0000ff",
   "keys": [
    {
     "raw": "KC_F12",
     "label": "F12",
     "kind": "basic"
    },
    {
     "raw": "KC_F1",
     "label": "F1",
     "kind": "basic"
    },
    {
     "raw": "KC_F2",
     "label": "F2",
     "kind": "basic"
    },
    {
     "raw": "KC_F3",
     "label": "F3",
     "kind": "basic"
    },
    {
     "raw": "KC_F4",
     "label": "F4",
     "kind": "basic"
    },
    {
     "raw": "KC_F5",
     "label": "F5",
     "kind": "basic"
    },
    {
     "raw": "KC_F6",
     "label": "F6",
     "kind": "basic"
    },
    {
     "raw": "KC_F7",
     "label": "F7",
     "kind": "basic"
    },
    {
     "raw": "KC_F8",
     "label": "F8",
     "kind": "basic"
    },
    {
     "raw": "KC_F9",
     "label": "F9",
     "kind": "basic"
    },
    {
     "raw": "KC_F10",
     "label": "F10",
     "kind": "basic"
    },
    {
     "raw": "KC_F11",
     "label": "F11",
     "kind": "basic"
    },
    {
     "raw": "KC_GRV",
     "label": "`",
     "kind": "basic"
    },
    {
     "raw": "KC_EXLM",
     "label": "!",
     "kind": "basic"
    },
    {
     "raw": "KC_AT",
     "label": "@",
     "kind": "basic"
    },
    {
     "raw": "KC_HASH",
     "label": "#",
     "kind": "basic"
    },
    {
     "raw": "KC_DLR",
     "label": "$",
     "kind": "basic"
    },
    {
     "raw": "KC_PERC",
     "label": "%",
     "kind": "basic"
    },
    {
     "raw": "KC_CIRC",
     "label": "^",
     "kind": "basic"
    },
    {
     "raw": "KC_AMPR",
     "label": "&",
     "kind": "basic"
    },
    {
     "raw": "KC_ASTR",
     "label": "*",
     "kind": "basic"
    },
    {
     "raw": "KC_LBRC",
     "label": "[",
     "kind": "basic"
    },
    {
     "raw": "KC_RBRC",
     "label": "]",
     "kind": "basic"
    },
    {
     "raw": "KC_PLUS",
     "label": "+",
     "kind": "basic"
    },
    {
     "raw": "KC_ESC",
     "label": "Esc",
     "kind": "basic"
    },
    {
     "raw": "KC_COLN",
     "label": ":",
     "kind": "basic"
    },
    {
     "raw": "KC_EQL",
     "label": "=",
     "kind": "basic"
    },
    {
     "raw": "KC_UNDS",
     "label": "_",
     "kind": "basic"
    },
    {
     "raw": "KC_PIPE",
     "label": "|",
     "kind": "basic"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "TO(_RAISE2)",
     "label": "\u2192 _RAISE2",
     "kind": "layer_switch",
     "layer": "_RAISE2"
    },
    {
     "raw": "KC_LPRN",
     "label": "(",
     "kind": "basic"
    },
    {
     "raw": "KC_RPRN",
     "label": ")",
     "kind": "basic"
    },
    {
     "raw": "KC_MINS",
     "label": "-",
     "kind": "basic"
    },
    {
     "raw": "KC_DQUO",
     "label": "\"",
     "kind": "basic"
    },
    {
     "raw": "KC_VOLU",
     "label": "Vol+",
     "kind": "basic"
    },
    {
     "raw": "KC_PSCR",
     "label": "PrtSc",
     "kind": "basic"
    },
    {
     "raw": "KC_ESC",
     "label": "Esc",
     "kind": "basic"
    },
    {
     "raw": "KC_GRV",
     "label": "`",
     "kind": "basic"
    },
    {
     "raw": "KC_LCBR",
     "label": "{",
     "kind": "basic"
    },
    {
     "raw": "KC_RCBR",
     "label": "}",
     "kind": "basic"
    },
    {
     "raw": "KC_CIRC",
     "label": "^",
     "kind": "basic"
    },
    {
     "raw": "KC_MUTE",
     "label": "Mute",
     "kind": "basic"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_LT",
     "label": "<",
     "kind": "basic"
    },
    {
     "raw": "KC_GT",
     "label": ">",
     "kind": "basic"
    },
    {
     "raw": "KC_QUES",
     "label": "?",
     "kind": "basic"
    },
    {
     "raw": "KC_VOLD",
     "label": "Vol-",
     "kind": "basic"
    },
    {
     "raw": "KC_MPLY",
     "label": "Play",
     "kind": "basic"
    },
    {
     "raw": "KC_MSTP",
     "label": "Stop",
     "kind": "basic"
    },
    {
     "raw": "KC_EQL",
     "label": "=",
     "kind": "basic"
    },
    {
     "raw": "KC_SCLN",
     "label": ";",
     "kind": "basic"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "TO(_RAISE2)",
     "label": "\u2192 _RAISE2",
     "kind": "layer_switch",
     "layer": "_RAISE2"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "KC_MFFD",
     "label": "FFwd",
     "kind": "basic"
    },
    {
     "raw": "KC_MRWD",
     "label": "RWnd",
     "kind": "basic"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    }
   ]
  },
  {
   "index": 3,
   "name": "_RAISE2",
   "phantom": false,
   "rgb": "#007e80",
   "keys": [
    {
     "raw": "KC_F12",
     "label": "F12",
     "kind": "basic"
    },
    {
     "raw": "KC_F1",
     "label": "F1",
     "kind": "basic"
    },
    {
     "raw": "KC_F2",
     "label": "F2",
     "kind": "basic"
    },
    {
     "raw": "KC_F3",
     "label": "F3",
     "kind": "basic"
    },
    {
     "raw": "KC_F4",
     "label": "F4",
     "kind": "basic"
    },
    {
     "raw": "KC_F5",
     "label": "F5",
     "kind": "basic"
    },
    {
     "raw": "KC_F6",
     "label": "F6",
     "kind": "basic"
    },
    {
     "raw": "KC_F7",
     "label": "F7",
     "kind": "basic"
    },
    {
     "raw": "KC_F8",
     "label": "F8",
     "kind": "basic"
    },
    {
     "raw": "KC_F9",
     "label": "F9",
     "kind": "basic"
    },
    {
     "raw": "KC_F10",
     "label": "F10",
     "kind": "basic"
    },
    {
     "raw": "KC_F11",
     "label": "F11",
     "kind": "basic"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "QK_BOOT",
     "label": "BOOT",
     "kind": "special"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "TO(_RAISE)",
     "label": "\u2192 _RAISE",
     "kind": "layer_switch",
     "layer": "_RAISE"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "QK_BOOT",
     "label": "BOOT",
     "kind": "special"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_LEFT",
     "label": "\u2190",
     "kind": "basic"
    },
    {
     "raw": "KC_UP",
     "label": "\u2191",
     "kind": "basic"
    },
    {
     "raw": "KC_DOWN",
     "label": "\u2193",
     "kind": "basic"
    },
    {
     "raw": "KC_RGHT",
     "label": "\u2192",
     "kind": "basic"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "KC_RPRN",
     "label": ")",
     "kind": "basic"
    },
    {
     "raw": "KC_MPRV",
     "label": "Prev",
     "kind": "basic"
    },
    {
     "raw": "KC_MPLY",
     "label": "Play",
     "kind": "basic"
    },
    {
     "raw": "KC_MNXT",
     "label": "Next",
     "kind": "basic"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_VOLU",
     "label": "Vol+",
     "kind": "basic"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_LPRN",
     "label": "(",
     "kind": "basic"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_VOLD",
     "label": "Vol-",
     "kind": "basic"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "TO(_RAISE)",
     "label": "\u2192 _RAISE",
     "kind": "layer_switch",
     "layer": "_RAISE"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    }
   ]
  },
  {
   "index": 4,
   "name": "_MOUSE",
   "phantom": false,
   "rgb": "#ff7fbe",
   "keys": [
    {
     "raw": "KC_F12",
     "label": "F12",
     "kind": "basic"
    },
    {
     "raw": "KC_F1",
     "label": "F1",
     "kind": "basic"
    },
    {
     "raw": "KC_F2",
     "label": "F2",
     "kind": "basic"
    },
    {
     "raw": "KC_F3",
     "label": "F3",
     "kind": "basic"
    },
    {
     "raw": "KC_F4",
     "label": "F4",
     "kind": "basic"
    },
    {
     "raw": "KC_F5",
     "label": "F5",
     "kind": "basic"
    },
    {
     "raw": "KC_F6",
     "label": "F6",
     "kind": "basic"
    },
    {
     "raw": "KC_F7",
     "label": "F7",
     "kind": "basic"
    },
    {
     "raw": "KC_F8",
     "label": "F8",
     "kind": "basic"
    },
    {
     "raw": "KC_F9",
     "label": "F9",
     "kind": "basic"
    },
    {
     "raw": "KC_F10",
     "label": "F10",
     "kind": "basic"
    },
    {
     "raw": "KC_F11",
     "label": "F11",
     "kind": "basic"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "MS_WHLU",
     "label": "Whl\u2191",
     "kind": "basic"
    },
    {
     "raw": "MS_WHLD",
     "label": "Whl\u2193",
     "kind": "basic"
    },
    {
     "raw": "KC_PLUS",
     "label": "+",
     "kind": "basic"
    },
    {
     "raw": "KC_MINS",
     "label": "-",
     "kind": "basic"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "MS_BTN3",
     "label": "Btn3",
     "kind": "basic"
    },
    {
     "raw": "MS_WHLL",
     "label": "Whl\u2190",
     "kind": "basic"
    },
    {
     "raw": "MS_WHLR",
     "label": "Whl\u2192",
     "kind": "basic"
    },
    {
     "raw": "MS_BTN2",
     "label": "Btn2",
     "kind": "basic"
    },
    {
     "raw": "MS_BTN1",
     "label": "Btn1",
     "kind": "basic"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "MS_UP",
     "label": "M\u2191",
     "kind": "basic"
    },
    {
     "raw": "MS_LEFT",
     "label": "M\u2190",
     "kind": "basic"
    },
    {
     "raw": "MS_DOWN",
     "label": "M\u2193",
     "kind": "basic"
    },
    {
     "raw": "MS_RGHT",
     "label": "M\u2192",
     "kind": "basic"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_LSFT",
     "label": "LShift",
     "kind": "basic"
    },
    {
     "raw": "KC_TAB",
     "label": "Tab",
     "kind": "basic"
    },
    {
     "raw": "MS_WHLU",
     "label": "Whl\u2191",
     "kind": "basic"
    },
    {
     "raw": "MS_WHLD",
     "label": "Whl\u2193",
     "kind": "basic"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_LCTL",
     "label": "LCtrl",
     "kind": "basic"
    },
    {
     "raw": "KC_LALT",
     "label": "LAlt",
     "kind": "basic"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "OSL(_LEADR)",
     "label": "OSL _LEADR",
     "kind": "oneshot_layer",
     "layer": "_LEADR"
    },
    {
     "raw": "KC_SPC",
     "label": "Space",
     "kind": "basic"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "KC_ENT",
     "label": "Enter",
     "kind": "basic"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "TD(LAYR_DOWN)",
     "label": "F",
     "kind": "tapdance",
     "td": "LAYR_DOWN"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_LCTL",
     "label": "LCtrl",
     "kind": "basic"
    }
   ]
  },
  {
   "index": 5,
   "name": "_LEADR",
   "phantom": false,
   "rgb": "#ff0000",
   "keys": [
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "LALT(KC_F4)",
     "label": "Alt+F4",
     "kind": "chord"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "EE_CLR",
     "label": "EE_CLR",
     "kind": "special"
    },
    {
     "raw": "LCTL(KC_GRV)",
     "label": "Ctrl+`",
     "kind": "chord"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "LCTL(LSFT(KC_E))",
     "label": "Ctrl+Shift+E",
     "kind": "chord"
    },
    {
     "raw": "LCTL(LSFT(KC_R))",
     "label": "Ctrl+Shift+R",
     "kind": "chord"
    },
    {
     "raw": "LCTL(LSFT(KC_T))",
     "label": "Ctrl+Shift+T",
     "kind": "chord"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "LCTL(LSFT(KC_O))",
     "label": "Ctrl+Shift+O",
     "kind": "chord"
    },
    {
     "raw": "LCTL(LSFT(KC_P))",
     "label": "Ctrl+Shift+P",
     "kind": "chord"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "LCTL(LSFT(KC_A))",
     "label": "Ctrl+Shift+A",
     "kind": "chord"
    },
    {
     "raw": "LCTL(LSFT(KC_S))",
     "label": "Ctrl+Shift+S",
     "kind": "chord"
    },
    {
     "raw": "LALT(LSFT(KC_D))",
     "label": "Alt+Shift+D",
     "kind": "chord"
    },
    {
     "raw": "LCTL(LSFT(KC_F))",
     "label": "Ctrl+Shift+F",
     "kind": "chord"
    },
    {
     "raw": "TO(_QWERTY)",
     "label": "\u2192 _QWERTY",
     "kind": "layer_switch",
     "layer": "_QWERTY"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "LALT(KC_UP)",
     "label": "Alt+\u2191",
     "kind": "chord"
    },
    {
     "raw": "LALT(KC_LEFT)",
     "label": "Alt+\u2190",
     "kind": "chord"
    },
    {
     "raw": "LALT(KC_DOWN)",
     "label": "Alt+\u2193",
     "kind": "chord"
    },
    {
     "raw": "LALT(KC_RIGHT)",
     "label": "Alt+Right",
     "kind": "chord"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "LCTL(LSFT(KC_Z))",
     "label": "Ctrl+Shift+Z",
     "kind": "chord"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "LCTL(LSFT(KC_C))",
     "label": "Ctrl+Shift+C",
     "kind": "chord"
    },
    {
     "raw": "LCTL(LSFT(KC_V))",
     "label": "Ctrl+Shift+V",
     "kind": "chord"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "LCTL(LSFT(KC_N))",
     "label": "Ctrl+Shift+N",
     "kind": "chord"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "DOT_SLS",
     "label": "./",
     "kind": "custom",
     "detail": "types ./"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_NO",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "KC_EQL",
     "label": "=",
     "kind": "basic"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "QK_LEAD",
     "label": "LEAD",
     "kind": "special"
    },
    {
     "raw": "TO(_LEADR)",
     "label": "\u2192 _LEADR",
     "kind": "layer_switch",
     "layer": "_LEADR"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "QK_LEAD",
     "label": "LEAD",
     "kind": "special"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "QK_LEAD",
     "label": "LEAD",
     "kind": "special"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    }
   ]
  },
  {
   "index": 6,
   "name": "_CAPSIND",
   "phantom": true,
   "rgb": "#fcff00",
   "keys": [
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    }
   ]
  },
  {
   "index": 7,
   "name": "_ALTLKIND",
   "phantom": true,
   "rgb": null,
   "keys": [
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    }
   ]
  },
  {
   "index": 8,
   "name": "_LOWLKIND",
   "phantom": true,
   "rgb": null,
   "keys": [
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    },
    {
     "raw": "_______",
     "label": "",
     "kind": "transparent"
    }
   ]
  }
 ],
 "tapDances": {
  "LAYR_DOWN": {
   "base": "F",
   "tap": "types F",
   "double": "LOWER one-shot; a second double-tap LOCKS LOWER",
   "triple": "LOWER locked (moved-to, not one-shot)",
   "hold": "MOUSE layer (layer_move)",
   "note": "From MOUSE: double-tap goes to LOWER one-shot and returns to MOUSE when the one-shot ends."
  },
  "LAYR_UP": {
   "base": "K",
   "tap": "types K",
   "double": "RAISE one-shot",
   "triple": "RAISE2 one-shot",
   "hold": "(nothing)",
   "note": null
  },
  "TD_S_OSM": {
   "base": "S",
   "tap": "types S",
   "double": "one-shot Shift",
   "triple": "(nothing)",
   "hold": "(nothing)",
   "note": null
  },
  "TD_J_OSM": {
   "base": "J",
   "tap": "types J",
   "double": "one-shot Shift",
   "triple": "(nothing)",
   "hold": "(nothing)",
   "note": null
  },
  "TD_D_OSM": {
   "base": "D",
   "tap": "types D",
   "double": "one-shot Alt",
   "triple": "toggle Alt mod-lock (held until triple-tapped again)",
   "hold": "(nothing)",
   "note": "Alt mod-lock lights the purple RGB layer and shows LOCK on the OLED."
  },
  "TD_G_CAPS": {
   "base": "G",
   "tap": "types G",
   "double": "toggle Caps Lock",
   "triple": "(nothing)",
   "hold": "(nothing)",
   "note": null
  },
  "TD_H_CAPS": {
   "base": "H",
   "tap": "types H",
   "double": "toggle Caps Lock",
   "triple": "(nothing)",
   "hold": "(nothing)",
   "note": null
  },
  "TD_V_TAB": {
   "base": "V",
   "tap": "types V",
   "double": "Tab",
   "triple": "(nothing)",
   "hold": "(nothing)",
   "note": null
  },
  "TD_Q_TILD": {
   "base": "Q",
   "tap": "types Q",
   "double": "~ (tilde)",
   "triple": "(nothing)",
   "hold": "(nothing)",
   "note": null
  },
  "TD_Z_GRV": {
   "base": "Z",
   "tap": "types Z",
   "double": "` (grave/backtick)",
   "triple": "(nothing)",
   "hold": "(nothing)",
   "note": null
  }
 },
 "leader": {
  "timeoutMs": 600,
  "sequences": [
   {
    "keys": [
     "S"
    ],
    "action": "Cmd+P then Cmd+K",
    "active": false,
    "note": "Global search (Cmd+P, Cmd+K)"
   },
   {
    "keys": [
     "H"
    ],
    "action": "Ctrl+H",
    "active": true,
    "note": "Control+H"
   },
   {
    "keys": [
     "C"
    ],
    "action": "Ctrl+Shift+C",
    "active": false,
    "note": "Copy (Ctrl+Shift+C)"
   },
   {
    "keys": [
     "A",
     "Q"
    ],
    "action": "Ctrl+A then Z then Q then Enter",
    "active": true,
    "note": "Quit minicom (Ctrl+A, Ctrl+Z, Ctrl+Q, Enter)"
   },
   {
    "keys": [
     "Y"
    ],
    "action": "Ctrl+X then Y then Enter",
    "active": true,
    "note": "Save and quit nano (Ctrl+X, Y, Enter)"
   },
   {
    "keys": [
     "LCtrl",
     "I"
    ],
    "action": "Ctrl+Alt+I",
    "active": true,
    "note": "SWAY: Lock/Hibernate (Ctrl+Alt+I)"
   },
   {
    "keys": [
     "J"
    ],
    "action": "Cmd+P",
    "active": false,
    "note": "SWAY: Move focus to right split (Cmd+P)"
   },
   {
    "keys": [
     "F"
    ],
    "action": "Cmd+'",
    "active": false,
    "note": "SWAY: Move focus to left split (Cmd+')"
   },
   {
    "keys": [
     "Del"
    ],
    "action": "LCmd+\u2191+\u2190",
    "active": false,
    "note": "Diagonal virtual desktop move (Cmd+Up+Left)"
   }
  ]
 },
 "customKeycodes": {
  "DOT_SLS": "types ./",
  "DIR_UP": "types ../",
  "DBL_DASH": "types --"
 },
 "timings": {
  "TAPPING_TERM": 265,
  "FLOW_TAP_TERM": 225,
  "LEADER_TIMEOUT": 600,
  "ONESHOT_TAP_TOGGLE": 2
 },
 "rgbLegend": [
  {
   "name": "RAISE",
   "hex": "#0000ff",
   "layer": "_RAISE",
   "trigger": "_RAISE active"
  },
  {
   "name": "RAISE2",
   "hex": "#007e80",
   "layer": "_RAISE2",
   "trigger": "_RAISE2 active"
  },
  {
   "name": "LOWER",
   "hex": "#00ff00",
   "layer": "_LOWER",
   "trigger": "_LOWER active"
  },
  {
   "name": "CAPS_LOCK",
   "hex": "#fcff00",
   "layer": "_CAPSIND",
   "trigger": "_CAPSIND active"
  },
  {
   "name": "LEADER",
   "hex": "#ff00fc",
   "layer": null,
   "trigger": "while a leader sequence is recording"
  },
  {
   "name": "LEADR",
   "hex": "#ff0000",
   "layer": "_LEADR",
   "trigger": "_LEADR active"
  },
  {
   "name": "CAPS",
   "hex": "#ffffff",
   "layer": null,
   "trigger": "pending one-shot Shift"
  },
  {
   "name": "MOUSE",
   "hex": "#ff7fbe",
   "layer": "_MOUSE",
   "trigger": "_MOUSE active"
  },
  {
   "name": "ALT_MOD",
   "hex": "#7e00ff",
   "layer": null,
   "trigger": "Alt/GUI mod active or mod-locked"
  }
 ],
 "baseColor": "#00320b"
};
